const getters = {
  sidebar: state => state.app.sidebar,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permissions: state => state.user.permissions,
  permission_routes: state => state.permission.routes,
  sidebarRouters: state => state.permission.sidebarRouters,
  // table getters
  menu: state => state.table.menu,
  userMenu: state => state.table.userMenu,
  menuLoading: state => state.table.menuLoading,
  tableTabs: state => state.table.tableTabs,
  tableLoading: state => state.table.tableLoading,
  activeTabData: state => state.table.activeTabData,
  tablePropDialogVisible: state => state.table.tablePropDialogVisible,
  tableDialogLoading: state => state.table.tableDialogLoading,
  tableDictDialogVisible: state => state.table.tableDictDialogVisible,
  tableExportDialogVisible: state => state.table.tableExportDialogVisible,
  tableDownloadDialogVisible: state => state.table.tableDownloadDialogVisible,
  tableSortDialogVisible: state => state.table.tableSortDialogVisible,
  tableFilterDialogVisible: state => state.table.tableFilterDialogVisible,
  tableAnalyseDialogVisible: state => state.table.tableAnalyseDialogVisible,
  addFolderDialogVisible: state => state.table.addFolderDialogVisible,
  addTableDialogVisible: state => state.table.addTableDialogVisible,
}
export default getters
